# Generated by Django 2.1.5 on 2021-07-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mame',
            new_name='name',
        ),
    ]
